# Generated by Django 5.0.1 on 2024-11-06 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileupdate', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
